### ISSUE TITLE
After scanning getting \r on each barcode scan

### ISSUE THREAD

**Issue by patelnirav48** [SocketMobile/singleentryswift-ios#10]
Why i getting \r at the end of decoded string? what to do for that to avoid?

**Comment by EricGlaenzer** [comment]
You can configure the scanner to remove the suffix. There is an API for that or a simple command barcode. This suffix configuration can be done once as it is persistent in the scanner. ScannerSettings app could also configure this setting.

**Comment by patelnirav48** [comment]
@EricGlaenzer  

I have configured scanner sdk singleentryswift-ios
Once i scan it i am getting \r at the end of scanned barcode in output of delegate method.

didReceiveDecodedData(_ decodedData: SKTCaptureDecodedData?, fromDevice device: CaptureHelperDevice, withResult result:SKTResult)
{
      var strBarcodeNumber = decodedData?.stringFromDecodedData()!
}

**Comment by EricGlaenzer** [comment]
Yes it is probably because the scanner suffix(postamble) is configured to \r. You can remove this suffix by using either a command barcode (available in the documentation that can be downloaded from our website: https://www.socketmobile.com/support/downloads ) or by using ScannerSettings app or by using the SDK API setPostamble. This is a one time setting. Now if the suffix is set to nothing and you're still getting a \r, that means it might be in the barcode (that is very unlikely though).

**Comment by patelnirav48** [comment]
@EricGlaenzer Thanks for your help. It's works.
